[quiniela]
# Reemplaza IP_PUBLICA con la salida vm_public_ip de Terraform.
IP_PUBLICA ansible_user=quiniela ansible_ssh_private_key_file=~/.ssh/id_ed25519

[quiniela:vars]
project_path=/opt/quiniela_predictor_mx
server_name=_
authorized_email=miguellponcej@gmail.com
